import Head from 'next/head';
// import Message from '../components/Message';
import { useEffect, useState } from 'react';
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Message from '../components/Message';

export default function Home() {

  //create a state with all the posts
  const [allPosts, setAllPosts] = useState(null);


  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({
        ...doc.data()
      })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);


  return (

    <div>
      <Head>
        <title>Twit your thought</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../src/MAN_TELECONFERENCE_WITH_TEAM-removebg.png" />
      </Head>
      <div className='my-12 text-lg font-extralight'>
        <h2 className='text-2xl my-2 mx-auto text-[#06B6D4]'>Thoughts by creative minds.</h2>
        <h1 className=" h-0.5 w-14 mb-10 bg-white rounded"></h1>
        {allPosts && allPosts.map((post) => (
          <Message key={post.id} {...post}>
          </Message>
        ))}
      </div>
    </div>
  )
}
