import Head from 'next/head';
// import Message from '../components/Message';
import { useEffect, useState } from 'react';
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import Message from '../components/Message';

export default function Home() {

  //create a state with all the posts
  const [allPosts, setAllPosts] = useState(null);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({
        ...doc.data()
      })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);


  return (

    <div>
      <Head>
        <title>Twit your thought</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='my-12 text-lg font-medium '>
        <h2 className='text-2xl text-white'>see what other people are saying</h2>
        {allPosts&&allPosts.map((post) => (
          <Message key={post.id} {...post}>
            
           </Message> 
        ))}
      
      </div>
    </div>
  )
}
